[workspace]

resolver = "2"

members = [
    "basics",
    "Control Flow",
    "Objects",
    "Pointers",
    #    "PythonRust",
    "Server",
    "Tokio",
    "Variables",
    "Axum Web",
    "ICP Blockchain",
    "ML and LLM", "Mutability", "Ownership",
]
